version: '3'
services:
  node:
    build: .
    network_mode: my-own-network
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=8080
    volumes:
      - ./logs:/usr/src/app/logs
      - ./db:/usr/src/app/src/common/daraBaseInMemory
  postgres:
    build: ./database
    image: postgres:13.3-alpine
    network_mode: my-own-network
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}