version: '3'
services:
  node:
    build: .
    image: "node:14-alpine"
    env_file:
      - .env
    networks:
      - backend
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=8080
    volumes:
      - ./logs:/usr/src/app/logs
      - ./db:/usr/src/app/src/common/daraBaseInMemory
  postgres:
    build: ./database
    image: postgres:13.3-alpine
    env_file:
      - .env
    networks:
      - backend
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
        - POSTGRES_USER:${DB_USERNAME}
        - POSTGRES_PASSWORD:${DB_PASSWORD}
        - POSTGRES_DB:${DB_NAME}
        - POSTGRES_PORT:${DB_PORT}
        - PGDATA:${PGDATA}
networks:
  backend:
    driver: bridge
    name: bridge-backend